# Generated by Django 2.2.5 on 2020-02-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0002_auto_20200216_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='semster',
            new_name='semester',
        ),
    ]
